### ISSUE TITLE
Build a new solver without recomputing prolongation 

### ISSUE THREAD

**Issue by chakshinglee** [LLNL/saamge#4]
Here is a feature that is desired: 

use some reference operator `A_0` to generate a hierarchy of prolongation matrices `P_i` (which is an expensive step), and then for a different operator `A_1`, make a multigrid solver for `A_1` using those `P_i`'s through RAP.

If there a way to do this currently in the code? If not, it would be great if it can be added.

**Comment by delyank** [comment]
See pull request #5 

Particularly you need the function

```
void adapt_update_operators(HypreParMatrix& A, ml_data_t &ml_data,
                            const MultilevelParameters &mlp, bool resmooth_interp)
```

**Comment by barker29** [comment]
@chakshinglee Can you see if PR #5 (now merged into master) does what you want so we can close this issue?
